sequenceDiagram
participant Developer
participant CoreSystems as Core Systems  MMS)
participant CICD as CI/CD Pipeline
participant Container Registry as Container Registry
participant DeploymentOrchestrator as Deployment Orchestrator
participant Factories

Developer ->>CoreSystems: Implement new feature
Developer->>CICD: Commit new update
CICD->>Container Registry: Docker image is built and pushed
DeploymentOrchestrator --> Container Registry: Latest image version is fetched
DeploymentOrchestrator ->> Factories: New feature is deployed
Factories --> DeploymentOrchestrator: New feature is reflected
